sudo: required
services:
  - docker

before_install:
  - docker build -t mahendiran-web1/docker-react -f Dockerfile.dev .

script:
  - docker run mahendiran-web1/docker-react npm run test -- --coverage
