sudo: required
services:
  - docker

before_install:
  - docker build -t Mahendiran-web/docker-react -f Dockerfile.dev .

script:
  - docker run Mahendiran-web/docker-react npm run test -- --coverage
